"""initial schema

Revision ID: 0c0396072aff
Revises:
Create Date: 2026-09-24 10:37:16.051945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c0396072aff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_digest",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("history_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ops", sa.Boolean(), nullable=False),
        sa.Column("queued_at", sa.DateTime(), nullable=False),
        sa.Column("flushed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("fired_at", sa.DateTime(), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_source", sa.String(length=20), nullable=True),
        sa.Column("price_ts", sa.DateTime(), nullable=True),
        sa.Column("fair_value", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("delivered", sa.JSON(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_history_fired", "alert_history", ["fired_at"], unique=False)
    op.create_index(op.f("ix_alert_history_rule_id"), "alert_history", ["rule_id"], unique=False)
    op.create_index(op.f("ix_alert_history_ticker"), "alert_history", ["ticker"], unique=False)
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("series_id", sa.String(length=200), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("hysteresis_pp", sa.Float(), nullable=False),
        sa.Column("cooldown_hours", sa.Float(), nullable=False),
        sa.Column("daily_cap", sa.Integer(), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("quiet_hours", sa.JSON(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_ticker"), "alert_rules", ["ticker"], unique=False)
    op.create_table(
        "assumption_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scenario", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assumption_sets_parent_id"), "assumption_sets", ["parent_id"], unique=False)
    op.create_index(op.f("ix_assumption_sets_ticker"), "assumption_sets", ["ticker"], unique=False)
    op.create_table(
        "concept_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_taxonomy", sa.String(length=20), nullable=False),
        sa.Column("source_concept", sa.String(length=300), nullable=False),
        sa.Column("canonical_field", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("sign", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("entity_override", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_taxonomy", "source_concept", "canonical_field", "entity_override", name="uq_concept_map"
        ),
    )
    op.create_index(op.f("ix_concept_map_canonical_field"), "concept_map", ["canonical_field"], unique=False)
    op.create_index(op.f("ix_concept_map_source_taxonomy"), "concept_map", ["source_taxonomy"], unique=False)
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("filer_type", sa.String(length=20), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=True),
        sa.Column("lei", sa.String(length=20), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("fiscal_year_end_month", sa.Integer(), nullable=True),
        sa.Column("taxonomies", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(op.f("ix_entities_ticker"), "entities", ["ticker"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_key", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("release_ts", sa.DateTime(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("end_ts", sa.DateTime(), nullable=True),
        sa.Column("reference_period", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("source_provider", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=600), nullable=True),
        sa.Column("linked_series", sa.JSON(), nullable=False),
        sa.Column("affected_tickers", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ingest_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_key", "reference_period", "release_date", name="uq_events_key_period_date"
        ),
    )
    op.create_index(op.f("ix_events_country"), "events", ["country"], unique=False)
    op.create_index("ix_events_country_release", "events", ["country", "release_ts"], unique=False)
    op.create_index(op.f("ix_events_event_key"), "events", ["event_key"], unique=False)
    op.create_index(op.f("ix_events_kind"), "events", ["kind"], unique=False)
    op.create_index("ix_events_release_ts", "events", ["release_ts"], unique=False)
    op.create_table(
        "facts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("canonical_field", sa.String(length=40), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=4), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_period", sa.String(length=4), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("unit_scale", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_concept", sa.String(length=300), nullable=True),
        sa.Column("accession_or_url", sa.String(length=500), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("filed_at", sa.Date(), nullable=True),
        sa.Column("restated_flag", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("doc_id", sa.Integer(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id",
            "canonical_field",
            "period_end",
            "period_type",
            "source",
            "restated_flag",
            name="uq_facts_key",
        ),
    )
    op.create_index("ix_facts_doc", "facts", ["doc_id"], unique=False)
    op.create_index(op.f("ix_facts_entity_id"), "facts", ["entity_id"], unique=False)
    op.create_index(
        "ix_facts_entity_period", "facts", ["entity_id", "period_type", "period_end"], unique=False
    )
    op.create_index(op.f("ix_facts_ticker"), "facts", ["ticker"], unique=False)
    op.create_table(
        "fair_value_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_source", sa.String(length=20), nullable=True),
        sa.Column("price_ts", sa.DateTime(), nullable=True),
        sa.Column("upside", sa.Float(), nullable=True),
        sa.Column("implied_growth", sa.Float(), nullable=True),
        sa.Column("assumption_set_id", sa.Integer(), nullable=True),
        sa.Column("inputs_snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "date", "model", "scenario", name="uq_fair_value_daily"),
    )
    op.create_index(
        "ix_fair_value_daily_ticker_model",
        "fair_value_daily",
        ["ticker", "model", "scenario", "date"],
        unique=False,
    )
    op.create_table(
        "fetch_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("op", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fetch_log_provider_ts", "fetch_log", ["provider", "ts"], unique=False)
    op.create_table(
        "industry_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.String(length=24), nullable=False),
        sa.Column("region", sa.String(length=16), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(length=400), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset", "region", "industry", "as_of", name="uq_industry_stats"),
    )
    op.create_index(op.f("ix_industry_stats_dataset"), "industry_stats", ["dataset"], unique=False)
    op.create_index(op.f("ix_industry_stats_industry"), "industry_stats", ["industry"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_job_id"), "job_runs", ["job_id"], unique=False)
    op.create_table(
        "layouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("model", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_usage_purpose"), "llm_usage", ["purpose"], unique=False)
    op.create_index(op.f("ix_llm_usage_ts"), "llm_usage", ["ts"], unique=False)
    op.create_table(
        "macro_mapping_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(length=8), nullable=False),
        sa.Column("indicator", sa.String(length=40), nullable=False),
        sa.Column("series_id", sa.String(length=200), nullable=False),
        sa.Column("transform", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country", "indicator", name="uq_macro_override"),
    )
    op.create_index(
        op.f("ix_macro_mapping_overrides_country"), "macro_mapping_overrides", ["country"], unique=False
    )
    op.create_table(
        "news_entities",
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("is_watchlist", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index(op.f("ix_news_entities_cik"), "news_entities", ["cik"], unique=False)
    op.create_table(
        "news_entity_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "alias", name="uq_entity_alias"),
    )
    op.create_index(op.f("ix_news_entity_aliases_ticker"), "news_entity_aliases", ["ticker"], unique=False)
    op.create_table(
        "news_sources",
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("cadence_s", sa.Integer(), nullable=False),
        sa.Column("license_note", sa.String(length=300), nullable=True),
        sa.Column("grey", sa.Boolean(), nullable=False),
        sa.Column("egress", sa.String(length=8), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_fetch_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=300), nullable=True),
        sa.Column("last_items", sa.Integer(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tickers", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("price_at_note", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pairs",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("a", sa.String(length=200), nullable=False),
        sa.Column("b", sa.String(length=200), nullable=False),
        sa.Column("transform_a", sa.String(length=20), nullable=True),
        sa.Column("transform_b", sa.String(length=20), nullable=True),
        sa.Column("freq", sa.String(length=10), nullable=False),
        sa.Column("lag_b", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pairs_a"), "pairs", ["a"], unique=False)
    op.create_index(op.f("ix_pairs_b"), "pairs", ["b"], unique=False)
    op.create_index(op.f("ix_pairs_country"), "pairs", ["country"], unique=False)
    op.create_table(
        "peer_sets",
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("sic", sa.String(length=8), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("peers", sa.JSON(), nullable=False),
        sa.Column("pins", sa.JSON(), nullable=False),
        sa.Column("excludes", sa.JSON(), nullable=False),
        sa.Column("as_of", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "prefs",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "quotes",
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("last", sa.Float(), nullable=False),
        sa.Column("prev_close", sa.Float(), nullable=True),
        sa.Column("change_pct", sa.Float(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "response_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("op", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_response_cache_expires_at"), "response_cache", ["expires_at"], unique=False)
    op.create_table(
        "series",
        sa.Column("series_id", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_key", sa.String(length=200), nullable=False),
        sa.Column("field_name", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("freq", sa.String(length=10), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("unit_mult", sa.Integer(), nullable=False),
        sa.Column("sa", sa.Boolean(), nullable=False),
        sa.Column("value_kind", sa.String(length=20), nullable=False),
        sa.Column("default_transform", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("publication_lag_days", sa.Integer(), nullable=False),
        sa.Column("release_rule", sa.String(length=120), nullable=True),
        sa.Column("supports_vintage", sa.Boolean(), nullable=False),
        sa.Column("vintage_policy", sa.String(length=12), nullable=False),
        sa.Column("plausible_min", sa.Float(), nullable=True),
        sa.Column("plausible_max", sa.Float(), nullable=True),
        sa.Column("license_note", sa.String(length=300), nullable=True),
        sa.Column("fallbacks", sa.JSON(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("series_id"),
    )
    op.create_index(op.f("ix_series_category"), "series", ["category"], unique=False)
    op.create_index(op.f("ix_series_country"), "series", ["country"], unique=False)
    op.create_index(op.f("ix_series_provider"), "series", ["provider"], unique=False)
    op.create_table(
        "statement_docs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("path_or_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("period_type", sa.String(length=4), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("extracted", sa.JSON(), nullable=True),
        sa.Column("validation", sa.JSON(), nullable=True),
        sa.Column("llm_usage", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statement_docs_entity_id"), "statement_docs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_statement_docs_status"), "statement_docs", ["status"], unique=False)
    op.create_index(op.f("ix_statement_docs_ticker"), "statement_docs", ["ticker"], unique=False)
    op.create_table(
        "valuation_macro_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=400), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "valuation_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=24), nullable=False),
        sa.Column("scenario", sa.String(length=16), nullable=False),
        sa.Column("assumption_set_id", sa.Integer(), nullable=True),
        sa.Column("inputs_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("value_per_share", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_source", sa.String(length=20), nullable=True),
        sa.Column("price_ts", sa.DateTime(), nullable=True),
        sa.Column("upside", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("inputs_summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_valuation_runs_ticker"), "valuation_runs", ["ticker"], unique=False)
    op.create_index(
        "ix_valuation_runs_ticker_created", "valuation_runs", ["ticker", "created_at"], unique=False
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "alert_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("last_eval_at", sa.DateTime(), nullable=True),
        sa.Column("last_fired_at", sa.DateTime(), nullable=True),
        sa.Column("fired_today", sa.Integer(), nullable=False),
        sa.Column("fired_day", sa.Date(), nullable=True),
        sa.Column("last_reason", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_state_rule_id"), "alert_state", ["rule_id"], unique=False)
    op.create_index("ix_alert_state_rule_ticker", "alert_state", ["rule_id", "ticker"], unique=True)
    op.create_table(
        "event_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("vintage_ts", sa.DateTime(), nullable=False),
        sa.Column("consensus", sa.Float(), nullable=True),
        sa.Column("consensus_source", sa.String(length=40), nullable=True),
        sa.Column("forecast_alt", sa.Float(), nullable=True),
        sa.Column("previous", sa.Float(), nullable=True),
        sa.Column("previous_revised", sa.Float(), nullable=True),
        sa.Column("actual", sa.Float(), nullable=True),
        sa.Column("actual_source", sa.String(length=40), nullable=True),
        sa.Column("unit", sa.String(length=24), nullable=True),
        sa.Column("surprise", sa.Float(), nullable=True),
        sa.Column("surprise_pct", sa.Float(), nullable=True),
        sa.Column("surprise_z", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_values_event_id"), "event_values", ["event_id"], unique=False)
    op.create_index("ix_event_values_event_vintage", "event_values", ["event_id", "vintage_ts"], unique=False)
    op.create_table(
        "raw_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=60), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_norm", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("simhash64", sa.BigInteger(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_raw_items_source_external"),
    )
    op.create_index("ix_raw_items_published", "raw_items", ["published_at"], unique=False)
    op.create_index(op.f("ix_raw_items_source_id"), "raw_items", ["source_id"], unique=False)
    op.create_index("ix_raw_items_url_hash", "raw_items", ["url_hash"], unique=False)
    op.create_table(
        "series_meta",
        sa.Column("series_id", sa.String(length=200), nullable=False),
        sa.Column("first_ts", sa.DateTime(), nullable=True),
        sa.Column("last_ts", sa.DateTime(), nullable=True),
        sa.Column("n_obs", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=20), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("rows_last_fetch", sa.Integer(), nullable=False),
        sa.Column("active_fallback", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.series_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("series_id"),
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watchlist_items_watchlist_id"), "watchlist_items", ["watchlist_id"], unique=False
    )
    op.create_table(
        "item_tickers",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["raw_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "ticker"),
    )
    op.create_index(op.f("ix_item_tickers_ticker"), "item_tickers", ["ticker"], unique=False)
    op.create_table(
        "news_filings",
        sa.Column("accession", sa.String(length=30), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("form", sa.String(length=20), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("filed_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("primary_doc_url", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["raw_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("accession"),
    )
    op.create_index("ix_filings_ticker_filed", "news_filings", ["ticker", "filed_at"], unique=False)
    op.create_table(
        "story_clusters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("canonical_item_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("n_items", sa.Integer(), nullable=False),
        sa.Column("n_publishers", sa.Integer(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("importance_parts", sa.JSON(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("why_it_matters", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("enriched_at", sa.DateTime(), nullable=True),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["canonical_item_id"], ["raw_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_story_clusters_last_seen", "story_clusters", ["last_seen"], unique=False)
    op.create_table(
        "cluster_items",
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("sim_method", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["story_clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["raw_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cluster_id", "item_id"),
    )
    op.create_index(op.f("ix_cluster_items_item_id"), "cluster_items", ["item_id"], unique=False)
    op.create_table(
        "news_enrichments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=40), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("why_it_matters", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["story_clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["raw_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_enrichments_cluster_id"), "news_enrichments", ["cluster_id"], unique=False)
    op.create_index("ix_news_enrichments_hash", "news_enrichments", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_enrichments_hash", table_name="news_enrichments")
    op.drop_index(op.f("ix_news_enrichments_cluster_id"), table_name="news_enrichments")
    op.drop_table("news_enrichments")
    op.drop_index(op.f("ix_cluster_items_item_id"), table_name="cluster_items")
    op.drop_table("cluster_items")
    op.drop_index("ix_story_clusters_last_seen", table_name="story_clusters")
    op.drop_table("story_clusters")
    op.drop_index("ix_filings_ticker_filed", table_name="news_filings")
    op.drop_table("news_filings")
    op.drop_index(op.f("ix_item_tickers_ticker"), table_name="item_tickers")
    op.drop_table("item_tickers")
    op.drop_index(op.f("ix_watchlist_items_watchlist_id"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_table("series_meta")
    op.drop_index("ix_raw_items_url_hash", table_name="raw_items")
    op.drop_index(op.f("ix_raw_items_source_id"), table_name="raw_items")
    op.drop_index("ix_raw_items_published", table_name="raw_items")
    op.drop_table("raw_items")
    op.drop_index("ix_event_values_event_vintage", table_name="event_values")
    op.drop_index(op.f("ix_event_values_event_id"), table_name="event_values")
    op.drop_table("event_values")
    op.drop_index("ix_alert_state_rule_ticker", table_name="alert_state")
    op.drop_index(op.f("ix_alert_state_rule_id"), table_name="alert_state")
    op.drop_table("alert_state")
    op.drop_table("watchlists")
    op.drop_index("ix_valuation_runs_ticker_created", table_name="valuation_runs")
    op.drop_index(op.f("ix_valuation_runs_ticker"), table_name="valuation_runs")
    op.drop_table("valuation_runs")
    op.drop_table("valuation_macro_cache")
    op.drop_index(op.f("ix_statement_docs_ticker"), table_name="statement_docs")
    op.drop_index(op.f("ix_statement_docs_status"), table_name="statement_docs")
    op.drop_index(op.f("ix_statement_docs_entity_id"), table_name="statement_docs")
    op.drop_table("statement_docs")
    op.drop_index(op.f("ix_series_provider"), table_name="series")
    op.drop_index(op.f("ix_series_country"), table_name="series")
    op.drop_index(op.f("ix_series_category"), table_name="series")
    op.drop_table("series")
    op.drop_index(op.f("ix_response_cache_expires_at"), table_name="response_cache")
    op.drop_table("response_cache")
    op.drop_table("quotes")
    op.drop_table("prefs")
    op.drop_table("peer_sets")
    op.drop_index(op.f("ix_pairs_country"), table_name="pairs")
    op.drop_index(op.f("ix_pairs_b"), table_name="pairs")
    op.drop_index(op.f("ix_pairs_a"), table_name="pairs")
    op.drop_table("pairs")
    op.drop_table("notes")
    op.drop_table("news_sources")
    op.drop_index(op.f("ix_news_entity_aliases_ticker"), table_name="news_entity_aliases")
    op.drop_table("news_entity_aliases")
    op.drop_index(op.f("ix_news_entities_cik"), table_name="news_entities")
    op.drop_table("news_entities")
    op.drop_index(op.f("ix_macro_mapping_overrides_country"), table_name="macro_mapping_overrides")
    op.drop_table("macro_mapping_overrides")
    op.drop_index(op.f("ix_llm_usage_ts"), table_name="llm_usage")
    op.drop_index(op.f("ix_llm_usage_purpose"), table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_table("layouts")
    op.drop_index(op.f("ix_job_runs_job_id"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_industry_stats_industry"), table_name="industry_stats")
    op.drop_index(op.f("ix_industry_stats_dataset"), table_name="industry_stats")
    op.drop_table("industry_stats")
    op.drop_index("ix_fetch_log_provider_ts", table_name="fetch_log")
    op.drop_table("fetch_log")
    op.drop_index("ix_fair_value_daily_ticker_model", table_name="fair_value_daily")
    op.drop_table("fair_value_daily")
    op.drop_index(op.f("ix_facts_ticker"), table_name="facts")
    op.drop_index("ix_facts_entity_period", table_name="facts")
    op.drop_index(op.f("ix_facts_entity_id"), table_name="facts")
    op.drop_index("ix_facts_doc", table_name="facts")
    op.drop_table("facts")
    op.drop_index("ix_events_release_ts", table_name="events")
    op.drop_index(op.f("ix_events_kind"), table_name="events")
    op.drop_index(op.f("ix_events_event_key"), table_name="events")
    op.drop_index("ix_events_country_release", table_name="events")
    op.drop_index(op.f("ix_events_country"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_entities_ticker"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_concept_map_source_taxonomy"), table_name="concept_map")
    op.drop_index(op.f("ix_concept_map_canonical_field"), table_name="concept_map")
    op.drop_table("concept_map")
    op.drop_index(op.f("ix_assumption_sets_ticker"), table_name="assumption_sets")
    op.drop_index(op.f("ix_assumption_sets_parent_id"), table_name="assumption_sets")
    op.drop_table("assumption_sets")
    op.drop_index(op.f("ix_alert_rules_ticker"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_alert_history_ticker"), table_name="alert_history")
    op.drop_index(op.f("ix_alert_history_rule_id"), table_name="alert_history")
    op.drop_index("ix_alert_history_fired", table_name="alert_history")
    op.drop_table("alert_history")
    op.drop_table("alert_digest")
    # ### end Alembic commands ###
